### ISSUE TITLE
Cannot read property 'range' of null

### ISSUE THREAD

**Issue by zeke** [denis-sokolov/strict-standard#8]
To reproduce:

``` sh
git clone https://github.com/electron/electron
cd electron
npm install strict-standard@2.0.4
./node_modules/.bin/strict-standard lib/renderer/api/remote.js
```

```
❯ ./node_modules/.bin/strict-standard lib/renderer/api/remote.js
strict-standard: Unexpected linter output:

TypeError: Cannot read property 'range' of null
    at isSafe (/Users/zeke/electron/electron/node_modules/eslint/lib/rules/no-loop-func.js:120:6)
    at Array.every (native)
    at EventEmitter.checkForLoops (/Users/zeke/electron/electron/node_modules/eslint/lib/rules/no-loop-func.js:168:25)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/zeke/electron/electron/node_modules/eslint/lib/util/node-event-generator.js:42:22)
    at CodePathAnalyzer.enterNode (/Users/zeke/electron/electron/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:591:23)
    at CommentEventGenerator.enterNode (/Users/zeke/electron/electron/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.traverser.traverse.enter (/Users/zeke/electron/electron/node_modules/eslint/lib/eslint.js:843:36)
    at Controller.__execute (/Users/zeke/electron/electron/node_modules/estraverse/estraverse.js:397:31)
```

**Comment by denis-sokolov** [comment]
Indeed, I reproduced it on your code base.

I disabled that single broken rule for now, as a quick investigation yielded no results. In particular, the rule works fine on its own, but not in combination with `standard-engine`.

**Comment by denis-sokolov** [comment]
`npm install strict-standard@2.0.5` will get you a working version.
